TIP  JSON Download Notification
CERP/education pull request #552
Opened 2022-05-27 18:37 UTC by mudssrali

2022-05-27 23:21 UTC, ZarishIqbal requested changes
Just one change is required.

2022-05-27 23:21 UTC, ZarishIqbal commented on web/src/pages/targeted-instruction/index.tsx
> +	const tipDataNotFetched = Object.keys(targetedInstruction).length === 0
Instead of checking the length of keys for `targetedInstruction`, we need to check the length for an inner object like `curriculum`. 
Reason: we assign default empty objects to the inner variables of `targetedInstruction`. 

`const tipDataNotFetched = Object.keys(targetedInstruction?.curriculum).length === 0`

2022-05-28 11:57 UTC, mudssrali commented on web/src/pages/targeted-instruction/index.tsx
> +	const tipDataNotFetched = Object.keys(targetedInstruction).length === 0
It's fine if we check keys only reason is that either we get the complete JSON or not. If we successfully get the JSON data then we store it otherwise it would be empty object.

2022-05-28 11:57 UTC, mudssrali commented on web/src/actions/index.ts
> +	clientType,
Need to check.

2022-05-29 10:35 UTC, merged